"""
#@author: pujasingh88
"""
import smtplib 
#from getpass import getpass
from email.mime.multipart import MIMEMultipart 
from email.mime.text import MIMEText 
from email.mime.base import MIMEBase 
from email import encoders
import pandas as pd
import random

import imaplib
import email



def OpenConnection(ServerName,PortNumber,UserName,Password):
    #establish a connection
    server = smtplib.SMTP('smtp.gmail.com', 587)
    print(server.ehlo())
    print(server.starttls())
    print(server.verify(UserName))
    try:
        server.login(UserName, Password)
        print(server.login(UserName, Password))
    except :
        print("Invalid Credentials")
    return server

def Santa(Employees):
    #determine santa for each participant
    receiver = Employees.copy()
    result= {}

    for i in Employees:
        Selection = Employees.copy()
        Selection.pop(Selection.index(i))
        options = list(set(Selection)&(set(receiver)))
        #create a list of participants yet to receive a gift
        choice = random.choice(options)
        result[i] = choice
        receiver.pop(receiver.index(choice))
    return result

def constructMessage(UserDetails):
    # construct an email message 

    msg = MIMEMultipart() 
    msg['From'] ='North Pole'
    msg['To'] = UserDetails[1]

    msg['Subject'] = 'Confidential!!!This is your secret'
    body = "Hey "+str(UserDetails[0]+",\n \n You are the secret santa (amigos secereto) for "+str(UserDetails[2] + ".\n \n This is an autogenerated email, we have no record of santa's and their giftees. For any other query, contact Puja Singh. \n \n Merry Christmas and Happy Disconnect."))
    msg.attach(MIMEText(body, 'plain')) 
    return msg
    
    
def sendemail(UserName,ReceiverID,server,Message):
    #send email to each participant mentioned in the excel sheet
    try:   
        server.sendmail(UserName,ReceiverID, Message.as_string())
    except ( ConnectionRefusedError):
    # report if your message was sent or there was an errors
        print('Failed to connect to the server. Bad connection settings?')
    except smtplib.SMTPServerDisconnected:
        print('Failed to connect to the server. Wrong user/password?')
    except smtplib.SMTPException as e:
        print('SMTP error occurred: ' + str(e))
    else:
        print('Sent')

      
def GetList(path):
    dflist=pd.read_csv(path)
    return dflist
    
def DeleteEmail(UserName,Password):
    mail = imaplib.IMAP4_SSL('imap.gmail.com')
    connection_message=mail.login(UserName, Password)
    print(connection_message)
    mail.select('"[Gmail]/Sent Mail"')
    result, data = mail.uid('search', None, 'SUBJECT "Hi Guys, This just a trial email for Secret Santa"') 
    #Search sent Email box based on Subject of the constructed email

    if result == 'OK':
        for num in data[0].split():
            result, data = mail.uid('fetch', num, '(RFC822)')
            if result == 'OK':
                email_message = email.message_from_bytes(data[0][1])    
                print('sender:' + email_message['Subject'])
            mail.uid('store', num, '+X-GM-LABELS', '\\Trash')
            #move the selected emails to Trash
    mail.select('[Gmail]/Trash')  # select all trash
    mail.store("1:*", '+FLAGS', '\\Deleted')
    mail.expunge()
    #delete the emails in Trash
    print('Emails Deleted')
    mail.close()
    mail.logout()
    return


if __name__=="__main__":
    UserName=input("Enter your Email Id here").strip()
    Password=input("Enter your Password").strip()
    # To get te sender's account access

    ServerName='smtp.gmail.com'
    PortNumber=587
    # modify the port number and ServerName as per Sender's  Email service provider

    Server=OpenConnection(ServerName,PortNumber,UserName,Password)
    #establish the connection

    Path=input("Enter the full path of the csv file").strip()
    DetailList=GetList(Path)
    #Get the list of participants from the excel file

    secret_santa = Santa(list(DetailList['Name']))
    #calculate secret santa for each participant

    for row_index,row in DetailList.iterrows():
        Userdetails = [row[0],row[1],secret_santa[row[0]]]
        MSG=constructMessage(Userdetails)
        sendemail(UserName,row[1],Server,MSG)
        print('Email Sent')
    #send email to each participant

    DeleteEmail(UserName,Password)
    # Delete the sent email from sender's email account based on Subject of the constructed email


